### ISSUE TITLE
Game crashes while riding the fox

### ISSUE THREAD

**Issue by qw3ry** [FishingCactus/NanotaleEarlyAccessBugs#21]
**Describe the bug**
After failing the defence of the fox (I guess it is intended to fail at some point), the character starts riding a ghost fox. Then, the main title appears. During the display of the main title, the fullscreen vanishes. Then, the fullscreen appears again, but black. Windows asks me if I want to end the process ("Process not responding").

**To Reproduce**
1. Go to the dying fox
2. Fail to defend it
3. See error

**Expected behavior**
The game should not crash

**Desktop (please complete the following information):**
 - Windows 10
 - AMD Radeon HD 5700 Series

**Additional context**
When windowed, the screen just freezes

**Comment by brunourbain** [comment]
Interesting, can you reproduce the bug or was it a one time? Might be linked to the graphics card but we'll have to investigate.

**Comment by qw3ry** [comment]
I can reproduce it. I also tried it with different graphic settings (windowed vs fullscreen, see above)
The Windows 10 should be fairly vanilla, I dual-boot and only use it for gaming.

**Comment by ZinaDerudder** [comment]
Cannot reproduce at the moment.
@qw3ry can you let us know if you are still facing that issue with the current Steam version?

**Comment by qw3ry** [comment]
Yes, the issue is still there. It changed slightly, however: The game stays alive until the main title vanishes again and the fox has reached an open space with a few animals. I assume this is the end of the cut-sequence. However, I do not regain control, and the game crashes. I estimate, the game runs roughly 10 seconds longer now.

I could run a version with logging enabled, if that helps. I could also debug into some places, but I guess you are not very eager to give me source code access.

**Comment by ZinaDerudder** [comment]
Hello Qw3ry.
Can you join me here your player.log file?
It should be at the same location than your savefile.
Check in C:\Users\[...]\AppData\LocalLow\Fishing Cactus\Nanotale

The best would be you try again with the very last version (we've pushed a new version on the 05th November), and reproduce the bug.
When the game crashes, take the player.log and drop it here.

We'll investigate what's wrong.

Thank you for your help, it's really much appreciated =)

**Comment by qw3ry** [comment]
I can still reproduce.

I uploaded the log file and the crash folder:
https://gofile.io/?c=PAYNo5

Please download the files, I have set the file share to expire.

**Comment by ZinaDerudder** [comment]
Hello Qw3ry.
Sorry for the late answer so many reports to check...
Apaprently, from what we've seen, it might occur that DirectX 11 is trying to access features that your GPU does not support, or that your graphic card does not meet the minimum required memory to run Nanotale.
There's not really much we can do at this point =/

**Comment by qw3ry** [comment]
Sad to hear that :( Thank you for your patience, though.

You may want to introduce a check for the required features on startup and display an appropriate error message to prevent further issues to be opened.

**Comment by ZinaDerudder** [comment]
Qwery, something you can try is running the game at the lowest graphic settings.
If the problem is really linked to a lack of graphical memory, it might work.

**Comment by ZinaDerudder** [comment]
Also, lower the resolution. It's another thing that might work. The lower the resolution, the few graphical memory is required.

**Comment by qw3ry** [comment]
This did work indeed, and I could finish early access. Thank you very much for your patience!
